# Generated by Django 4.0.3 on 2022-03-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBatch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('harvest_year', models.DateField()),
                ('price_pr_kg_usd', models.IntegerField()),
            ],
            options={
                'db_table': 'coffee_batch',
            },
        ),
        migrations.CreateModel(
            name='CoffeeDrinker',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'coffee_drinker',
            },
        ),
        migrations.CreateModel(
            name='CoffeeFarm',
            fields=[
                ('coffee_farm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('meters_above_sea', models.IntegerField()),
                ('region', models.CharField(max_length=400)),
                ('country', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'coffee_farm',
            },
        ),
        migrations.CreateModel(
            name='ProcessingType',
            fields=[
                ('processing_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'processing_type',
            },
        ),
        migrations.CreateModel(
            name='UnprocessedBean',
            fields=[
                ('unprocessed_bean_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unprocessed_coffee_bean',
            },
        ),
        migrations.CreateModel(
            name='RoastedCoffee',
            fields=[
                ('coffee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('price_per_kg_nok', models.IntegerField()),
                ('roast_date', models.DateField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffeebatch', to='coffeeApp.coffeebatch')),
            ],
            options={
                'db_table': 'roasted_coffee',
            },
        ),
        migrations.CreateModel(
            name='CoffeeTasting',
            fields=[
                ('tasting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=400)),
                ('score', models.IntegerField()),
                ('taste_date', models.DateField()),
                ('coffee_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roastedcoffee', to='coffeeApp.roastedcoffee')),
                ('user_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffeedrinker', to='coffeeApp.coffeedrinker')),
            ],
            options={
                'db_table': 'coffee_tasting',
            },
        ),
        migrations.AddField(
            model_name='coffeebatch',
            name='coffee_farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffeefarm', to='coffeeApp.coffeefarm'),
        ),
        migrations.AddField(
            model_name='coffeebatch',
            name='processing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_type', to='coffeeApp.processingtype'),
        ),
        migrations.AddField(
            model_name='coffeebatch',
            name='unprocessed_beans',
            field=models.ManyToManyField(to='coffeeApp.unprocessedbean'),
        ),
    ]
