# Generated by Django 4.0.3 on 2022-03-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastedCoffee',
            fields=[
                ('coffee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('price_per_kg_nok', models.IntegerField()),
                ('roast_date', models.DateField()),
            ],
            options={
                'db_table': 'roasted_coffee',
            },
        ),
        migrations.RenameField(
            model_name='coffeetasting',
            old_name='user_fk',
            new_name='user_id_fk',
        ),
        migrations.AddField(
            model_name='coffeetasting',
            name='coffee_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roastedcoffee', to='coffeeApp.roastedcoffee'),
        ),
    ]
